title: Meta Human
description: Meta Human Always Fancy

base_uri: https://ipfs.io/ipfs/Qme42XjH7tBpvqyCqQFoa6UmbXehnRbwk5NDVATCSVQvf3

# Change the seed until a million dollar collection is generated.
seed: 888

# Number of unique images you are going to create.
number: 10000

start: 1

size:
  width: 2000
  height: 2000

traits:
  background:
    red:
      prob: 10
    orange:
      prob: 10
    yellow:
      prob: 10
    green:
      prob: 10
    blue:
      prob: 10
    navy:
      prob: 10
    purple:
      prob: 10
    hanbok 1:
      prob: 10
    hanbok 2:
      prob: 10
    black:
      prob: 10

  type:
    XX:
      prob: 25
    XXB:
      prob: 25
    XY:
      prob: 25
    XYB:
      prob: 25
  eyes:
    motionless:
      prob: 30
    closed:
      prob: 20
    frown:
      prob: 20
    angry:
      prob: 15
    looking:
      prob: 11.5
    happy:
      prob: 2.5
    scar:
      prob: 1
  mouth:
    motionless:
      prob: 60
    angry:
      prob: 15
    cigarette:
      prob: 10
    flower:
      prob: 10
    beard:
      prob: 5
  ear:
    earrings:
      prob: 30
    small_earrings:
      prob: 30
    lv_earrings:
      prob: 20
    chrome_hearts:
      prob: 5
    piercing:
      prob: 5
    earphone:
      prob: 4
    airpod:
      prob: 3
    none:
      prob: 3
  neck:
    headphone:
      prob: 60
    meta_headphone:
      prob: 20
    pendant:
      prob: 10
    chrome_hearts:
      prob: 4
    heavy_tattoo:
      prob: 1
    light_tattoo:
      prob: 1
    barcode:
      prob: 1
    animal_tattoo:
      prob: 1
    anti-human_tattoo:
      prob: 1
    none:
      prob: 1
  mask:
    half_mask:
      prob: 30
    anti_mask:
      prob: 30
    traditional_mask:
      prob: 30
    none:
      prob: 10
  hair:
    dread:
      prob: 40
    short cut:
      prob: 30
    normal:
      prob: 10
    bald:
      prob: 10
    topknot:
      prob: 10
  hidden hair:
    short cut:
      prob: 40
    normal:
      prob: 20
    bald:
      prob: 20
    topknot:
      prob: 20
  faceAccessories:
    gentle_monster_glasses:
      prob: 20
    retro_glasses:
      prob: 20
    chrome_hearts_glasses:
      prob: 20
    meta_glasses:
      prob: 20
    eye_patch:
      prob: 10
    none:
      prob: 10
  clothing:
    t-shirt:
      prob: 30
    jumper:
      prob: 20
    hood:
      prob: 10
    shirt:
      prob: 10
    jacket:
      prob: 10
    polo_t-shirt:
      prob: 10
    tech_wear:
      prob: 4
    best:
      prob: 4
    hanbok:
      prob: 1
    none:
      prob: 1
  offhand:
    cigarette:
      prob: 30
    supreme bat:
      prob: 25
    meta_hand:
      prob: 7
    ring:
      prob: 7
    white_wine:
      prob: 5
    red_wine:
      prob: 5
    coke:
      prob: 5
    stading_microphone:
      prob: 4
    supreme_water_gun:
      prob: 3
    mobile_phone:
      prob: 3
    coffee:
      prob: 2
    shoes:
      prob: 2
    electronic_guitar:
      prob: 1
    drumstick:
      prob: 0.5
    none:
      prob: 0.5
  headgear:
    ball_cap:
      prob: 0.5
    camp_cap:
      prob: 0.5
    bucket_hat:
      prob: 0.5
    hood_hat:
      prob: 0.5
    prada_hunting_cap:
      prob: 0.5
    none:
      prob: 0.5
  effect:
    smoke:
      prob: 30
    light smoke:
      prob: 30
    neon:
      prob: 10
    light:
      prob: 10
    flame:
      prob: 10
    none:
      prob: 10
