# Number of unique images you are going to create.
number: 1000

traits:
  background:
    Gray:
      prob: 40
    Sky Blue:
      prob: 30
    Blue:
      prob: 20
    Purple:
      prob: 10

  type:
    XY:
      prob: 40
    XY Brown:
      prob: 40
    XY Diamond:
      prob: 20

  eyes:
    Angry:
      prob: 10
    Closed:
      prob: 10
    Dot:
      prob: 10
    Dot Long:
      prob: 7
    Emotionless A:
      prob: 7
    Emotionless B:
      prob: 7
    Emotionless C:
      prob: 7
    God:
      prob: 7
    Huh:
      prob: 7
    Looking A:
      prob: 7
    Looking B:
      prob: 7
    Odd Eye:
      prob: 7
    Scar:
      prob: 7

  mouth:
    Simple:
      prob: 20
    Bite:
      prob: 20
    Laugh:
      prob: 20
    Miso Light:
      prob: 20
    Scar:
      prob: 20

  ear:
    Earrings:
      prob: 50
    None:
      prob: 50

  neck:
    Tattoo:
      prob: 30
    Headphone:
      prob: 30
    None:
      prob: 40

  mask:
    Meta Mask:
      prob: 30
    None:
      prob: 50

  hair:
    Wave:
      prob: 100

  h_headgear_hair:
    Wave:
      prob: 100

  faceAccessories:
    Plastic Glasses:
      prob: 50
    None:
      prob: 50

  clothing:
    Fur:
      prob: 30
    Red:
      prob: 35
    Blue:
      prob: 35

  offhand:
    Cigarette:
      prob: 40
    Bat:
      prob: 30
    Meta Cat:
      prob: 20
    None:
      prob: 10

  headgear:
    Cap:
      prob: 50
    None:
      prob: 50

  effect:
    Smoke:
      prob: 30
    None:
      prob: 70
