# Number of unique images you are going to create.
number: 1000

traits:
  background:
    Gray:
      prob: 40
    Sky Blue:
      prob: 30
    Blue:
      prob: 20
    Purple:
      prob: 10

  type:
    XX:
      prob: 40
    XX Brown:
      prob: 40
    XX Diamond:
      prob: 20

  eyes:
    Emotionless A:
      prob: 10
    Emotionless B:
      prob: 10
    Emotionless C:
      prob: 10
    Dot:
      prob: 10
    God:
      prob: 10
    Odd Eye:
      prob: 10
    Closed:
      prob: 10
    Looking A:
      prob: 10
    Wink:
      prob: 10
    Miso:
      prob: 10

  mouth:
    Simple:
      prob: 50
    Miso:
      prob: 50

  ear:
    Earrings:
      prob: 50
    None:
      prob: 50

  neck:
    Tattoo:
      prob: 30
    Headphone:
      prob: 30
    Chocker:
      prob: 30
    None:
      prob: 10

  mask:
    Meta Mask:
      prob: 30
    None:
      prob: 50

  hair:
    Wave:
      name: Wave
      prob: 50
    Shortcut:
      prob: 50

  h_headgear_hair:
    Wave:
      prob: 50
    Shortcut:
      prob: 50

  faceAccessories:
    Plastic Glasses:
      prob: 50
    None:
      prob: 50


  clothing:
    Normal:
      prob: 30
    Fur:
      prob: 25
    Hanbok:
      prob: 25
    Gray:
      prob: 20

  offhand:
    Cigarette:
      prob: 40
    Bat:
      prob: 30
    Meta Cat:
      prob: 20
    None:
      prob: 10

  headgear:
    Cap:
      prob: 50
    None:
      prob: 50

  effect:
    Smoke:
      prob: 30
    None:
      prob: 70
