# Number of unique images you are going to create.
number: 100

traits:
  background:
    gray:
      name: Gray
      prob: 40
    sky_blue:
      name: Sky Blue
      prob: 30
    blue:
      name: Blue
      prob: 20
    purple:
      name: Purple
      prob: 10

  type:
    xx:
      name: XX
      prob: 40
    xx_brown:
      name: XX Brown
      prob: 40
    xx_diamond:
      name: XX Diamond
      prob: 20

  eyes:
    emotionless_a:
      name: Emotionless A
      prob: 10
    emotionless_b:
      name: Emotionless B
      prob: 10
    emotionless_c:
      name: Emotionless C
      prob: 10
    dot:
      name: Dot
      prob: 10
    god:
      name: God
      prob: 10
    odd_eye:
      name: Odd Eye
      prob: 10
    closed:
      name: Closed
      prob: 10
    looking_a:
      name: Looking A
      prob: 10
    wink:
      name: Wink
      prob: 10
    miso:
      name: Miso
      prob: 10

  mouth:
    simple:
      name: Simple
      prob: 50
    miso:
      name: Miso
      prob: 50

  ear:
    earrings:
      name: Earrings
      prob: 50
    none:
      name: None
      prob: 50

  neck:
    chocker:
      name: Chocker
      prob: 50
    none:
      name: None
      prob: 50

  mask:
    meta_mask:
      name: Meta Mask
      prob: 30
    none:
      name: None
      prob: 50

  hair:
    wave:
      name: Wave
      prob: 100

  h_headgear_hair:
    wave:
      name: Wave
      prob: 100

  faceAccessories:
    plastic_glasses:
      name: Plastice Glasses
      prob: 50
    none:
      name: None
      prob: 50

  h_hair:
    wave:
      name: Wave
      prob: 100

  clothing:
    normal:
      name: Normal
      prob: 40
    hanbok:
      name: Hanbok
      prob: 30
    gray:
      name: Hanbok
      prob: 30

  offhand:
    cigarette:
      name: Cigarette
      prob: 40
    bat:
      name: Bat
      prob: 30
    meta_cat:
      name: Meta Cat
      prob: 20
    none:
      name: None
      prob: 10

  headgear:
    cap:
      name: Cap
      prob: 50
    none:
      name: None
      prob: 50

  effect:
    smoke:
      name: Smoke
      prob: 30
    none:
      name: None
      prob: 70
