# Number of unique images you are going to create.
number: 100

traits:
  background:
    gray:
      name: Gray
      prob: 40
    sky_blue:
      name: Sky Blue
      prob: 30
    blue:
      name: Blue
      prob: 20
    purple:
      name: Purple
      prob: 10

  type:
    xy:
      name: XY
      prob: 40
    xy_brown:
      name: XY Brown
      prob: 40
    xy_diamond:
      name: XY Diamond
      prob: 20

  eyes:
    angry:
      name: Angry
      prob: 10
    closed:
      name: Closed
      prob: 10
    dot:
      name: Dot
      prob: 10
    dot_long:
      name: Dot Long
      prob: 7
    emotionless_a:
      name: Emotionless A
      prob: 7
    emotionless_b:
      name: Emotionless B
      prob: 7
    emotionless_c:
      name: Emotionless C
      prob: 7
    god:
      name: God
      prob: 7
    huh:
      name: Huh
      prob: 7
    looking_a:
      name: Looking A
      prob: 7
    looking_b:
      name: Looking B
      prob: 7
    odd_eye:
      name: Odd Eye
      prob: 7
    scar:
      name: Scar
      prob: 7

  mouth:
    simple:
      name: Simple
      prob: 20
    bite:
      name: Bite
      prob: 20
    laugh:
      name: Laugh
      prob: 20
    miso_light:
      name: Miso Light
      prob: 20
    scar:
      name: Scar
      prob: 20

  ear:
    earrings:
      name: Earrings
      prob: 50
    none:
      name: None
      prob: 50

  neck:
    none:
      name: None
      prob: 100

  mask:
    meta_mask:
      name: Meta Mask
      prob: 30
    none:
      name: None
      prob: 50

  hair:
    wave:
      name: Wave
      prob: 100

  h_headgear_hair:
    wave:
      name: Wave
      prob: 100

  faceAccessories:
    plastic_glasses:
      name: Plastice Glasses
      prob: 50
    none:
      name: None
      prob: 50

  clothing:
    red:
      name: Normal
      prob: 50
    blue:
      name: Blue
      prob: 50

  offhand:
    cigarette:
      name: Cigarette
      prob: 40
    bat:
      name: Bat
      prob: 30
    meta_cat:
      name: Meta Cat
      prob: 20
    none:
      name: None
      prob: 10

  headgear:
    cap:
      name: Cap
      prob: 50
    none:
      name: None
      prob: 50

  effect:
    smoke:
      name: Smoke
      prob: 30
    none:
      name: None
      prob: 70
