title: Meta Human
description: Meta Human Always Fancy

base_uri: https://ipfs.io/ipfs/Qme42XjH7tBpvqyCqQFoa6UmbXehnRbwk5NDVATCSVQvf3

# Change the seed until a million dollar collection is generated.
# seed: 888

start: 1

size:
  width: 2000
  height: 2000

# Z-index order of image from bottom to top
order:
  - background
  - h_effect
  - h_faceAccessories
  - type
  - eyes
  - mouth
  - neck
  - mask
  - hair
  - h_headgear_hair
  - faceAccessories
  - ear
  - clothing
  - offhand
  - headgear
  - h_hair
  - effect