name: LiveLikeHoneyBadger

description: lorem ipsum

base_uri: database.com/

# Change the seed until a million dollar collection is generated.
seed: 222

# Number of unique images you are going to create.
number: 1

start: 1


traits:
  background:
    values:
      pink:
        name: Pink
        prob: 100
        src: layer/background/pink.png

  body:
    values:
      gray:
        name: Gray
        prob: 100
        src: layer/body/gray.png

  wear:
    values:
      check_honey_pink:
        name: Check Honey Pink
        prob: 100
        src: layer/wear/check_honey_pink.png
  face:
    values:
      gray:
        name: Gray
        prob: 100
        src: layer/face/gray.png

  headgear:
    values:
      taxi:
        name: Taxi
        prob: 100
        src: layer/headgear/taxi.png

  honey_bird:
    values:
      propeller:
        name: Propeller
        prob: 100
        src: layer/honeybird/propeller.png

  eye:
    values:
      heart:
        name: Heart
        prob: 100
        src: layer/eye/heart.png

  speech:
    values:
      snake:
        name: Snake
        prob: 100
        src: layer/speech/snake.png